/**
 * 測試用-Swagger UI 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: skyi989@ymail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import StockData from '../model/StockData';
import TaiwanTotalIndex from '../model/TaiwanTotalIndex';

/**
* StockController service.
* @module api/StockControllerApi
* @version 1.0
*/
export default class StockControllerApi {

    /**
    * Constructs a new StockControllerApi. 
    * @alias module:api/StockControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getTaiwanTotalIndex operation.
     * @callback module:api/StockControllerApi~getTaiwanTotalIndexCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/TaiwanTotalIndex>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 取得加權指數
     * 取得加權指數
     * @param {Object} opts Optional parameters
     * @param {Date} [] 
     * @param {module:api/StockControllerApi~getTaiwanTotalIndexCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/TaiwanTotalIndex>}
     */
    getTaiwanTotalIndex(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        '日期': opts['']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [TaiwanTotalIndex];
      return this.apiClient.callApi(
        '/home/getTaiwanTotalIndex', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getTodaySingleStockData operation.
     * @callback module:api/StockControllerApi~getTodaySingleStockDataCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/StockData>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 取得個股收盤資訊
     * 取得個股收盤資訊
     * @param {Object} opts Optional parameters
     * @param {Date} [date] 
     * @param {String} [code] 
     * @param {module:api/StockControllerApi~getTodaySingleStockDataCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/StockData>}
     */
    getTodaySingleStockData(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'date': opts['date'],
        'code': opts['code']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [StockData];
      return this.apiClient.callApi(
        '/home/getSingleStockData', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getTodayStockData operation.
     * @callback module:api/StockControllerApi~getTodayStockDataCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/StockData>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 取得今日上市股票收盤資訊
     * 取得今日上市股票收盤資訊
     * @param {module:api/StockControllerApi~getTodayStockDataCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/StockData>}
     */
    getTodayStockData(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [StockData];
      return this.apiClient.callApi(
        '/home/getTodayStockData', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
