/**
 * 測試用-Swagger UI 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: skyi989@ymail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerUi);
  }
}(this, function(expect, SwaggerUi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SwaggerUi.TaiwanTotalIndex();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TaiwanTotalIndex', function() {
    it('should create an instance of TaiwanTotalIndex', function() {
      // uncomment below and update the code to test TaiwanTotalIndex
      //var instance = new SwaggerUi.TaiwanTotalIndex();
      //expect(instance).to.be.a(SwaggerUi.TaiwanTotalIndex);
    });

    it('should have the property date (base name: "date")', function() {
      // uncomment below and update the code to test the property date
      //var instance = new SwaggerUi.TaiwanTotalIndex();
      //expect(instance).to.be();
    });

    it('should have the property openingIndex (base name: "openingIndex")', function() {
      // uncomment below and update the code to test the property openingIndex
      //var instance = new SwaggerUi.TaiwanTotalIndex();
      //expect(instance).to.be();
    });

    it('should have the property highestIndex (base name: "highestIndex")', function() {
      // uncomment below and update the code to test the property highestIndex
      //var instance = new SwaggerUi.TaiwanTotalIndex();
      //expect(instance).to.be();
    });

    it('should have the property lowestIndex (base name: "lowestIndex")', function() {
      // uncomment below and update the code to test the property lowestIndex
      //var instance = new SwaggerUi.TaiwanTotalIndex();
      //expect(instance).to.be();
    });

    it('should have the property closingIndex (base name: "closingIndex")', function() {
      // uncomment below and update the code to test the property closingIndex
      //var instance = new SwaggerUi.TaiwanTotalIndex();
      //expect(instance).to.be();
    });

  });

}));
